version: '2'
services:
    westation-postgresql:
        image: postgres:9.6.5
        volumes:
             - ~/volumes/jhipster/westation/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=westation
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
